#!/usr/bin/python3
import random
number = random.randint(-10000, 10000)
if number < 0:
	ones = abs(number) % 10
	ones = ones * -1
else:
	ones = number % 10

if ones > 5:
	print("Last digit of {} is {} and greater than 5".format(ones, number))
elif ones < 6 and ones != 0:
	print("Last digit of {} is {} is less than 6 and not 0".format(ones, number))
elif ones == 0:
	print("Last digit of {} is {} and is 0".format(ones, number))
